### ISSUE TITLE
Missing argument 2 for Craft\GravatarVariable::url()

### ISSUE THREAD

**Issue by alecritson** [ehousestudio/craft_gravatar#2]
Hey, thanks for the plugin!

This error is thrown when using the template variables, it looks like its expecting the options array in `GravatarVariable.php`, changing `$options` to `$options = array()` would fix this.

**Comment by ryanshrum** [comment]
Hi Alec, thanks for pointing this out. Would you mind posting your use case so I can test it with all the other options? Thanks.

**Comment by alecritson** [comment]
Sure no problem, first I used:

```
{{ craft.gravatar.url(currentUser.email) }}
```
which was when I saw the error above, but now I'm using:

```
{% set options = {
 'default' : 'mm'
}%}

{{ craft.gravatar.url(currentUser.email, options) }}
```

Hope that helps :)
